import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import * as T from '../public/vendor/three.module.js';
import {jackLayout} from '../public/jack-layout.js';import {jackBenchDirection} from '../public/guide-orientation.js';import {calculate} from '../public/shopping-calc.js';
const data=JSON.parse(fs.readFileSync(new URL('../public/data/flat-shopping-list.json',import.meta.url),'utf8'));
test('Full-height uprights plus shorter feet keep the same jack outline and fit stock with kerf',()=>{for(const h of [96,120]){const d=jackLayout(h);assert.equal(d.jackUprightLength,h===120?96:72);assert.equal(d.jackFootLength,h===120?44.5:32.5);assert.equal(d.jackFootLength+d.jackBoardWidth,d.foot);assert.ok(2*d.jackFootLength+2*.125<=96);assert.equal(d.jackUprightLength,d.jackH);}});
test('Gusset has three fixings in each member, inside its triangular face',()=>{for(const h of [96,120]){const d=jackLayout(h);let upright=0,foot=0;for(const [z,y]of d.gussetFixings){assert.ok(z>0&&y>0&&z+y<8);if(z<3.5){upright++;assert.ok(y<d.jackH);}else{foot++;assert.ok(y<3.5&&z<d.foot);}}assert.equal(upright,3);assert.equal(foot,3);}});
test('Both mirrored jack uprights project above their feet in the default bench view',()=>{const camera=new T.PerspectiveCamera(38,1,.1,100),center=new T.Vector3(0,0,1.2);camera.position.copy(center).add(new T.Vector3(...jackBenchDirection()).normalize().multiplyScalar(5));camera.lookAt(center);camera.updateMatrixWorld();for(const x of [-.4,.4]){const base=new T.Vector3(x,0,0).project(camera),top=new T.Vector3(x,0,96*.0254).project(camera);assert.ok(top.y>base.y);}});
test('Tall-panel supports replace one 10-foot board with one 8-foot board per panel',()=>{const r=data.variants['10x4'].supportRequirements;assert.equal(r.board14,3);assert.equal(r.board14long,2);const rows=calculate(data,'10x4',8,true,false);assert.equal(rows.find(r=>r.id==='board14').purchaseQuantity,32,'8 seam-backers + 16 uprights + 8 foot-pair boards');assert.equal(rows.find(r=>r.id==='board14long').purchaseQuantity,16);assert.match(data.variants['10x4'].cuts.join(' '),/44.5 in feet from one 8 ft board/);});
// Inspect the real generated meshes rather than only the dimension helper.
test('Actual jack meshes meet at a butt joint with no overlap or gap',async()=>{
 const url=name=>new URL('../public/'+name,import.meta.url).href;
 const utils=fs.readFileSync(new URL('../public/vendor/BufferGeometryUtils.js',import.meta.url),'utf8').replaceAll("'three'",JSON.stringify(url('vendor/three.module.js')));
 let source=fs.readFileSync(new URL('../public/model.js',import.meta.url),'utf8').replaceAll("'three'",JSON.stringify(url('vendor/three.module.js'))).replace("'./vendor/BufferGeometryUtils.js'",JSON.stringify('data:text/javascript;base64,'+Buffer.from(utils).toString('base64')));
 for(const name of ['platform.js','jack-attachment.js','jack-layout.js','wall-appearance.js','platform-finish.js'])source=source.replace(JSON.stringify('./'+name),JSON.stringify(url(name))).replace("'./"+name+"'",JSON.stringify(url(name)));
 const load=T.TextureLoader.prototype.load;T.TextureLoader.prototype.load=()=>new T.Texture();let module;try{module=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));}finally{T.TextureLoader.prototype.load=load;}
 const bounds=o=>{o.geometry.computeBoundingBox();return o.geometry.boundingBox;},close=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
 for(const h of [96,120]){const panel=module.panel(h),d=jackLayout(h);for(const side of ['Left','Right']){const u=bounds(panel.getObjectByName(side+' jack upright')),f=bounds(panel.getObjectByName(side+' jack foot'));close(u.min.y,0);close(f.min.y,0);close(u.max.y,d.jackH*module.inch);close(u.min.z,f.max.z);close(f.max.z-f.min.z,d.jackFootLength*module.inch);close(u.max.z-f.min.z,d.foot*module.inch);}module.dispose(panel);}
});
