import test from 'node:test';import assert from 'node:assert/strict';
import {mountProgressMotion} from '../public/progress-motion.js';
function fixture(native){
 const animations=[],listeners=[],observers=[];let root;
 const rect={top:200,left:20,width:360,height:434};
 function node(type='plain'){const n={style:{},dataset:{},children:[],classList:{add(){}},setAttribute(){},append(x){this.children.push(x)},before(){},remove(){this.removed=true},getBoundingClientRect:()=>type==='viewport'?{...rect,height:250}:rect,animate(frames,options){const a={frames,options,paused:false,cancelled:false,pause(){this.paused=true},play(){this.played=true},cancel(){this.cancelled=true}};animations.push(a);return a;},insertAdjacentHTML(){},querySelector(s){return this.nodes[s]},cloneNode(){return root}};return n;}
 root=node();const ring=node(),caption=node(),legend=node(),bg=node();bg.firstElementChild=node();ring.nodes={svg:node(),strong:node(),'div>span':node()};caption.nodes={p:node()};legend.children=[node(),node(),node(),node()];root.nodes={'.pj-ring':ring,'.pj-progress-caption':caption,'.pj-stage-legend':legend,'.pj-morph-background':bg,'.pj-morph-bloom':node()};
 const hero=node();hero.nodes=root.nodes;const host={hidden:false},aside={scrollHeight:100,clientHeight:100},viewport=node('viewport'),scroll={scrollTop:0};
 const values={document:{createElement:()=>node(),querySelector:()=>viewport,scrollingElement:scroll},window:{addEventListener:(event)=>listeners.push(event),removeEventListener(){}},getComputedStyle:()=>({position:'relative',overflowY:'visible'}),matchMedia:()=>({matches:false}),CSS:{supports:()=>true},ScrollTimeline:native?class{constructor(options){this.options=options}}:undefined,ResizeObserver:class{observe(){}disconnect(){this.disconnected=true}},IntersectionObserver:class{constructor(cb){this.cb=cb;observers.push(this)}observe(){}disconnect(){this.disconnected=true}}};
 const original=Object.fromEntries(Object.keys(values).map(k=>[k,globalThis[k]]));Object.assign(globalThis,values);
 return {hero,host,aside,animations,listeners,observers,restore:()=>Object.assign(globalThis,original)};
}
test('Native progress delegates frame updates to ScrollTimeline and installs no scroll listener',()=>{const f=fixture(true);try{const stop=mountProgressMotion(f.hero,f.host,f.aside);assert.ok(f.animations.length>10);assert.ok(f.animations.every(a=>a.options.timeline&&a.options.rangeStart==='200px'&&a.options.rangeEnd==='440px'));assert.ok(!f.listeners.includes('scroll'));assert.equal(f.observers.length,0);stop();assert.ok(f.animations.every(a=>a.cancelled));}finally{f.restore();}});
test('Unsupported browsers animate only at threshold crossings and reverse when scrolling back',()=>{const f=fixture(false);try{const stop=mountProgressMotion(f.hero,f.host,f.aside);assert.ok(f.animations.every(a=>a.paused&&a.currentTime===0));f.observers[0].cb([{boundingClientRect:{top:-1}}]);assert.ok(f.animations.every(a=>a.played&&a.playbackRate===1));f.observers[0].cb([{boundingClientRect:{top:1}}]);assert.ok(f.animations.every(a=>a.playbackRate===-1));assert.ok(!f.listeners.includes('scroll'));stop();assert.ok(f.observers[0].disconnected);}finally{f.restore();}});

test('Collapsed background retains an unscaled 18px corner radius throughout its native animation',()=>{const f=fixture(true);try{const stop=mountProgressMotion(f.hero,f.host,f.aside);const background=f.animations.find(a=>a.frames[0].clipPath);assert.ok(background);assert.equal(background.frames.at(-1).clipPath,'inset(0px 0px 350px 0px round 18px)');assert.ok(background.frames.every(k=>k.clipPath.endsWith('round 18px)')&&!k.transform));stop();}finally{f.restore();}});
